#!/usr/bin/env bash
set -euo pipefail

sdk_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
repo_root="$(CDPATH= cd -- "$sdk_root/../.." && pwd)"
spec="$repo_root/openapi/templiqx-operations-v1.yaml"
models="$sdk_root/Templiqx.Adapter/Generated/OperationsV1.cs"
metadata="$sdk_root/Templiqx.Adapter/Generated/GeneratedMeta.cs"
project="$sdk_root/Templiqx.Adapter/Templiqx.Adapter.csproj"
check=false

case "${1:-}" in
"") ;;
--check) check=true ;;
*)
  echo "Usage: $0 [--check]" >&2
  exit 2
  ;;
esac

temp_dir="$(mktemp -d "${TMPDIR:-/tmp}/templiqx-dotnet-sdk.XXXXXX")"
trap 'rm -rf "$temp_dir"' EXIT

temp_models="$temp_dir/OperationsV1.cs"
temp_metadata="$temp_dir/GeneratedMeta.cs"

generator_version="7.17.0"
generator_sha256="25d6bd8273dd2be99979d544b62ea43f0ce1975f1aa582678b5093d1e7fcfce8"
generator_dir="$sdk_root/.tools"
generator_jar="$generator_dir/openapi-generator-cli-$generator_version.jar"
generator_url="https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/$generator_version/openapi-generator-cli-$generator_version.jar"

if [[ -x /opt/homebrew/opt/openjdk/bin/java ]]; then
  java=/opt/homebrew/opt/openjdk/bin/java
elif command -v java >/dev/null 2>&1; then
  java="$(command -v java)"
else
  echo "Java is required to regenerate the .NET DTOs" >&2
  exit 1
fi

mkdir -p "$generator_dir"
if [[ ! -f $generator_jar ]] ||
  [[ "$(shasum -a 256 "$generator_jar" | awk '{print $1}')" != "$generator_sha256" ]]; then
  curl -fsSL "$generator_url" -o "$generator_jar.download"
  actual_sha256="$(shasum -a 256 "$generator_jar.download" | awk '{print $1}')"
  if [[ $actual_sha256 != "$generator_sha256" ]]; then
    echo "OpenAPI Generator checksum mismatch" >&2
    rm -f "$generator_jar.download"
    exit 1
  fi
  mv "$generator_jar.download" "$generator_jar"
fi

generated_dir="$temp_dir/openapi-generator"
generator_log="$temp_dir/openapi-generator.log"
if ! "$java" -jar "$generator_jar" generate \
  -g csharp \
  -i "$spec" \
  -o "$generated_dir" \
  --global-property models,modelDocs=false,modelTests=false,supportingFiles=Option.cs:ClientUtils.cs \
  --model-package Generated \
  --additional-properties=packageName=Templiqx.Adapter,targetFramework=net9.0,nullableReferenceTypes=true \
  >"$generator_log" 2>&1; then
  cat "$generator_log" >&2
  exit 1
fi

generated_files=(
  "$generated_dir/src/Templiqx.Adapter/Client/ClientUtils.cs"
  "$generated_dir/src/Templiqx.Adapter/Client/Option.cs"
  "$generated_dir/src/Templiqx.Adapter/Generated/"*.cs
)

{
  echo "// <auto-generated />"
  echo "// Generated by OpenAPI Generator $generator_version (models only)."
  echo "#nullable enable"
  echo
  awk '/^using / { print }' "${generated_files[@]}" | LC_ALL=C sort -u
  echo
  for generated_file in "${generated_files[@]}"; do
    sed -n '/^namespace /,$p' "$generated_file"
    echo
  done
} >"$temp_models"

openapi_version="$(awk '/^  version:/ { gsub(/[\047\042]/, "", $2); print $2; exit }' "$spec")"
openapi_digest="sha256:$(shasum -a 256 "$spec" | awk '{print $1}')"
sdk_version="$(sed -n 's:.*<Version>\([^<]*\)</Version>.*:\1:p' "$project" | head -n 1)"

if [[ -z $openapi_version || -z $sdk_version ]]; then
  echo "Could not read the OpenAPI or SDK version" >&2
  exit 1
fi

cat >"$temp_metadata" <<EOF
// <auto-generated />
namespace Templiqx.Adapter.Generated;

public static class GeneratedMeta
{
    public const string GeneratedOpenApiVersion = "$openapi_version";
    public const string GeneratedOpenApiDigest = "$openapi_digest";
    public const string GeneratedSdkVersion = "$sdk_version";
}
EOF

if [[ $check == true ]]; then
  drift=false
  if ! cmp -s "$models" "$temp_models"; then
    echo "Generated .NET DTOs are stale: $models" >&2
    diff -u "$models" "$temp_models" || true
    drift=true
  fi
  if ! cmp -s "$metadata" "$temp_metadata"; then
    echo "Generated .NET metadata is stale: $metadata" >&2
    diff -u "$metadata" "$temp_metadata" || true
    drift=true
  fi
  if [[ $drift == true ]]; then
    exit 1
  fi
  echo "Generated .NET DTOs and metadata are current."
else
  mkdir -p "$(dirname "$models")"
  cp "$temp_models" "$models"
  cp "$temp_metadata" "$metadata"
  echo "Generated .NET DTOs: $models"
  echo "Generated .NET metadata: $metadata"
fi
