use std::{
    env, fs,
    io::Write,
    path::PathBuf,
    process::{Command, Stdio},
};

use quote::quote;
use schemars::schema::RootSchema;
use serde_json::{Map, Value, json};
use sha2::{Digest, Sha256};
use typify::{TypeSpace, TypeSpaceSettings};

fn rewrite_refs(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if let Some(Value::String(reference)) = map.get_mut("$ref")
                && let Some(name) = reference.strip_prefix("#/components/schemas/")
            {
                *reference = format!("#/definitions/{name}");
            }
            for value in map.values_mut() {
                rewrite_refs(value);
            }
        }
        Value::Array(values) => values.iter_mut().for_each(rewrite_refs),
        _ => {}
    }
}

fn yaml_get<'a>(value: &'a serde_yaml::Value, keys: &[&str]) -> &'a serde_yaml::Value {
    keys.iter().fold(value, |current, key| {
        current
            .get(*key)
            .unwrap_or_else(|| panic!("missing YAML key {}", keys.join(".")))
    })
}

fn yaml_str(value: &serde_yaml::Value, keys: &[&str]) -> String {
    yaml_get(value, keys)
        .as_str()
        .unwrap_or_else(|| panic!("YAML value {} is not a string", keys.join(".")))
        .to_owned()
}

fn rustfmt(source: &str) -> Result<String, Box<dyn std::error::Error>> {
    let mut child = Command::new("rustfmt")
        .args(["--emit", "stdout", "--edition", "2024"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .expect("piped stdin")
        .write_all(source.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        return Err("rustfmt failed for generated DTOs".into());
    }
    Ok(String::from_utf8(output.stdout)?)
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let sdk_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = sdk_root.join("../..").canonicalize()?;
    let spec_path = repo_root.join("openapi/templiqx-operations-v1.yaml");
    let matrix_path = repo_root.join("openapi/compatibility-matrix.yaml");
    let output_path = sdk_root.join("src/generated.rs");

    let spec_bytes = fs::read(&spec_path)?;
    let spec: serde_yaml::Value = serde_yaml::from_slice(&spec_bytes)?;
    let matrix: serde_yaml::Value = serde_yaml::from_slice(&fs::read(&matrix_path)?)?;
    let schemas = yaml_get(&spec, &["components", "schemas"]);
    let mut definitions: Map<String, Value> = serde_json::to_value(schemas)?
        .as_object()
        .expect("components.schemas must be an object")
        .clone();
    definitions.values_mut().for_each(rewrite_refs);

    let properties: Map<String, Value> = definitions
        .keys()
        .map(|name| {
            (
                name.clone(),
                json!({ "$ref": format!("#/definitions/{name}") }),
            )
        })
        .collect();
    let root_value = json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "TempliqxOperationsV1",
        "type": "object",
        "properties": properties,
        "definitions": definitions,
    });
    let root: RootSchema = serde_json::from_value(root_value)?;
    let mut type_space = TypeSpace::new(
        TypeSpaceSettings::default()
            .with_struct_builder(false)
            .with_map_type("::std::collections::BTreeMap"),
    );
    type_space.add_root_schema(root)?;

    let generated_file: syn::File = syn::parse2(quote! { #type_space })?;
    let mut generated = String::from(
        "// @generated by `scripts/generate.sh` from openapi/templiqx-operations-v1.yaml.\n\
         // Do not edit by hand.\n\n",
    );
    generated.push_str(&prettyplease::unparse(&generated_file));

    let openapi_version = yaml_str(&spec, &["info", "version"]);
    let digest = format!("sha256:{:x}", Sha256::digest(&spec_bytes));
    let contract_format = yaml_str(&matrix, &["contractFormat"]);
    let engine_version = yaml_str(&matrix, &["engineVersion"]);
    let sdk_version = env!("CARGO_PKG_VERSION");
    generated.push_str(&format!(
        "\n/// Codegen metadata used by the compatibility self-check.\n\
         pub const GENERATED_OPENAPI_VERSION: &str = {openapi_version:?};\n\
         pub const GENERATED_OPENAPI_DIGEST: &str = {digest:?};\n\
         pub const GENERATED_CONTRACT_FORMAT: &str = {contract_format:?};\n\
         pub const GENERATED_ENGINE_VERSION: &str = {engine_version:?};\n\
         pub const GENERATED_SDK_VERSION: &str = {sdk_version:?};\n"
    ));
    generated = rustfmt(&generated)?;

    let matrix_digest = yaml_str(&matrix, &["openApiDigest"]);
    if matrix_digest != digest {
        return Err(format!(
            "OpenAPI digest {digest} does not match compatibility matrix {matrix_digest}"
        )
        .into());
    }

    if env::args().any(|arg| arg == "--check") {
        let current = fs::read_to_string(&output_path).unwrap_or_default();
        if current != generated {
            return Err(format!("generated DTOs are stale: {}", output_path.display()).into());
        }
        println!("Generated Rust DTOs are current: {}", output_path.display());
    } else {
        fs::write(&output_path, generated)?;
        println!("Generated Rust DTOs: {}", output_path.display());
    }

    Ok(())
}
