# generated by datamodel-codegen:
#   filename:  templiqx-operations-v1.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class JsonValue(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Arbitrary JSON value owned by Templiqx contract schemas or runtime output.'
        ),
    ]


class Status(StrEnum):
    ok = 'ok'
    ready = 'ready'
    not_ready = 'not_ready'


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    api_version: str
    request_id: str | None = None


class TransportError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(examples=['TQX_TRANSPORT_TIMEOUT'])]
    message: str
    request_id: str | None = None


class Severity(StrEnum):
    error = 'error'
    warning = 'warning'
    info = 'info'


class SourceSpan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    line: Annotated[int, Field(ge=0)]
    column: Annotated[int, Field(ge=0)]
    end_line: Annotated[int, Field(ge=0)]
    end_column: Annotated[int, Field(ge=0)]


class PackageSignature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_id: str
    algorithm: str
    value: str


class FieldSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Annotated[JsonValue, Field(alias='schema')]
    required: bool | None = None
    description: str | None = None


class CapabilityProfileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[str] | None = None


class RenderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputs: dict[str, JsonValue] | None = None
    context: dict[str, JsonValue] | None = None


class UpdatePackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: str | None = None
    description: str | None = None


class CreatePackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    version: str


class SignPackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_id: str


class VerifyPackageTrustRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strict: bool | None = False


class CapabilitiesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[str] | None = None


class RunEvalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract: str
    fixture_id: str
    capabilities: list[str] | None = None


class DiffContractRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    right_package: str
    right_contract: str


class MigrateLegacyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    dialect: str
    source: str
    aliases: JsonValue


class RenderDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    template: str
    data: JsonValue
    output: str
    workspace: str | None = None


class InspectDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    dialect: str
    template: str
    aliases: Annotated[JsonValue | None, Field(validate_default=True)] = Field(
        default_factory=lambda: JsonValue({})
    )


class InspectDocumentResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    report: JsonValue


class ContractSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    id: str
    version: str
    fingerprint: str
    summary: str | None = None
    inputs: list[str] | None = None
    context: list[str] | None = None
    capabilities: list[str] | None = None
    component_count: Annotated[int | None, Field(ge=0)] = None
    components: list[str] | None = None
    unresolved_references: list[str] | None = None
    fix_hints: list[str] | None = None


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str
    content: str


class CompiledInteraction(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    contract_id: str
    messages: list[Message]
    output_schema: JsonValue
    required_capabilities: list[str]
    runtime_policy: dict[str, JsonValue] | None = None


class AdapterDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    version: str
    capabilities: list[str]


class StreamEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Delta']
    text: str


class StreamEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ToolCallDelta']
    name: str
    arguments_fragment: str


class StreamEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Failed']
    code: str
    message: str


class Diagnostic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    severity: Severity
    message: str
    file: str | None = None
    json_pointer: str | None = None
    span: SourceSpan | None = None
    help: str | None = None


class PackageManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_version: str
    package: str
    version: str
    description: str | None = None
    contracts: list[str] | None = None
    components: list[str] | None = None
    evals: list[str] | None = None
    migrations: list[str] | None = None
    templates: list[str] | None = None
    provenance: dict[str, str] | None = None
    signatures: list[PackageSignature] | None = None


class Contract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_version: str
    id: str
    version: str
    description: str | None = None
    inputs: dict[str, FieldSpec] | None = None
    context: dict[str, FieldSpec] | None = None
    capabilities: list[str] | None = None
    messages: list[dict[str, Any]]
    output_schema: JsonValue
    runtime_policy: dict[str, JsonValue] | None = None
    extensions: dict[str, JsonValue] | None = None
    components: dict[str, JsonValue] | None = None
    provenance: dict[str, str] | None = None
    evals: list[JsonValue] | None = None


class CompileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render: RenderRequest | None = None
    capabilities: list[str] | None = None


class ExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render: RenderRequest | None = None
    capabilities: list[str] | None = None
    fixture_output: JsonValue | None = None
    stream: bool | None = False


class ExecutionReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter: AdapterDescriptor
    request_fingerprint: str
    output_fingerprint: str
    output: JsonValue
    output_schema_valid: bool


class StreamEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Complete']
    receipt: ExecutionReceipt


class StreamEvent(RootModel[StreamEvent1 | StreamEvent2 | StreamEvent3 | StreamEvent4]):
    root: StreamEvent1 | StreamEvent2 | StreamEvent3 | StreamEvent4


class OperationEnvelopeBase(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    api_version: Literal['templiqx/v1alpha1']
    operation: str
    ok: bool
    diagnostics: list[Diagnostic]
    fingerprints: dict[str, str]
    stream_events: list[StreamEvent] | None = None


class CatalogEnvelope(OperationEnvelopeBase):
    result: list[str] | None = None


class StringListEnvelope(OperationEnvelopeBase):
    result: list[str] | None = None


class JsonValueEnvelope(OperationEnvelopeBase):
    result: JsonValue | None = None


class PackageListEnvelope(OperationEnvelopeBase):
    result: list[PackageManifest] | None = None


class PackageEnvelope(OperationEnvelopeBase):
    result: PackageManifest | None = None


class ContractEnvelope(OperationEnvelopeBase):
    result: Contract | None = None


class SummaryEnvelope(OperationEnvelopeBase):
    result: ContractSummary | None = None


class CompiledInteractionEnvelope(OperationEnvelopeBase):
    result: CompiledInteraction | None = None


class ExecutionReceiptEnvelope(OperationEnvelopeBase):
    result: ExecutionReceipt | None = None


class InspectDocumentEnvelope(OperationEnvelopeBase):
    result: InspectDocumentResult | None = None

# Codegen metadata used by the compatibility self-check.
GENERATED_OPENAPI_VERSION = '1.0.0-alpha.1'
GENERATED_OPENAPI_DIGEST = 'sha256:7cd1c2251d87c27a77efcc35523209d8916cc59d222c8f770b095ecc078a1914'
GENERATED_SDK_VERSION = '0.1.0'
