# generated by datamodel-codegen:
#   filename:  templiqx-operations-v1.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class JsonValue(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description='Arbitrary JSON value owned by Templiqx contract schemas or runtime output.'
        ),
    ]


class Status(StrEnum):
    ok = 'ok'
    ready = 'ready'
    not_ready = 'not_ready'


class HealthStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    api_version: str
    request_id: str | None = None


class TransportError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(examples=['TQX_TRANSPORT_TIMEOUT'])]
    message: str
    request_id: str | None = None


class Severity(StrEnum):
    error = 'error'
    warning = 'warning'
    info = 'info'


class SourceSpan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    line: Annotated[int, Field(ge=0)]
    column: Annotated[int, Field(ge=0)]
    end_line: Annotated[int, Field(ge=0)]
    end_column: Annotated[int, Field(ge=0)]


class QualityIdentifier(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Portable ASCII identifier, bounded to 128 UTF-8 bytes by Templiqx.',
            max_length=128,
            min_length=1,
            pattern='^[A-Za-z0-9._:-]+$',
        ),
    ]


class QualityFingerprint(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Host-attested or Templiqx-computed SHA-256-compatible hexadecimal fingerprint.',
            max_length=64,
            min_length=64,
            pattern='^[A-Fa-f0-9]{64}$',
        ),
    ]


class MetricUnit(StrEnum):
    ratio_ppm = 'ratio_ppm'
    milliseconds = 'milliseconds'
    token_count = 'token_count'
    currency_microunits = 'currency_microunits'


class MetricAggregation(StrEnum):
    binary_ratio_ppm = 'binary_ratio_ppm'
    mean = 'mean'
    sum = 'sum'
    p95_nearest_rank = 'p95_nearest_rank'


class ObjectiveDirection(StrEnum):
    maximize = 'maximize'
    minimize = 'minimize'


class EligibilityComparator(StrEnum):
    gte = 'gte'
    lte = 'lte'


class TokenKind(StrEnum):
    prompt = 'prompt'
    completion = 'completion'
    total = 'total'


class CandidateQualityFailureReason(StrEnum):
    schema = 'schema'
    assertion = 'assertion'
    invalid_output = 'invalid_output'


class InfrastructureFailureReason(StrEnum):
    transport = 'transport'
    timeout = 'timeout'
    rate_limit = 'rate_limit'
    provider_unavailable = 'provider_unavailable'
    provider_internal = 'provider_internal'
    cancellation = 'cancellation'
    budget = 'budget'
    evaluator_infrastructure = 'evaluator_infrastructure'


class BinaryScorer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: QualityIdentifier
    metric_id: QualityIdentifier
    claimed_scorer_fingerprint: QualityFingerprint


class QualityObjective(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: QualityIdentifier
    metric_id: QualityIdentifier
    unit: MetricUnit
    aggregation: MetricAggregation
    direction: ObjectiveDirection
    claimed_measurement_profile_fingerprint: QualityFingerprint
    currency_code: Annotated[str | None, Field(pattern='^[A-Z]{3}$')] = None
    token_kind: TokenKind | None = None


class EligibilityRule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: QualityIdentifier
    metric_id: QualityIdentifier
    comparator: EligibilityComparator
    unit: MetricUnit
    threshold: Annotated[int, Field(ge=0, le=9007199254740991)]


class QualityPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: QualityIdentifier
    replicates_per_fixture: Annotated[int, Field(ge=1, le=20)]
    minimum_semantic_cases: Annotated[int, Field(ge=0, le=9007199254740991)]
    maximum_infrastructure_failure_ppm: Annotated[int, Field(ge=0, le=1000000)]
    claimed_evaluator_profile_fingerprint: QualityFingerprint
    claimed_model_profile_fingerprint: QualityFingerprint
    binary_scorers: Annotated[list[BinaryScorer], Field(max_length=16, min_length=1)]
    objectives: Annotated[list[QualityObjective], Field(max_length=16, min_length=1)]
    eligibility_rules: Annotated[list[EligibilityRule], Field(min_length=1)]


class TrialOutcome1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['scored']


class TrialOutcome2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['candidate_quality_failure']
    reason: CandidateQualityFailureReason


class TrialOutcome3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['infrastructure_failure']
    reason: InfrastructureFailureReason


class TrialOutcome(RootModel[TrialOutcome1 | TrialOutcome2 | TrialOutcome3]):
    root: TrialOutcome1 | TrialOutcome2 | TrialOutcome3


class MetricObservation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metric_id: QualityIdentifier
    unit: MetricUnit
    value: Annotated[int, Field(ge=0, le=9007199254740991)]
    claimed_measurement_profile_fingerprint: QualityFingerprint
    currency_code: Annotated[str | None, Field(pattern='^[A-Z]{3}$')] = None
    token_kind: TokenKind | None = None


class ComputedQualityIdentities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package_fingerprint: QualityFingerprint
    base_contract_fingerprint: QualityFingerprint
    fixture_set_fingerprint: QualityFingerprint
    quality_policy_fingerprint: QualityFingerprint
    request_fingerprint: QualityFingerprint


class ClaimedQualityIdentities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claimed_candidate_contract_fingerprint: QualityFingerprint
    claimed_evaluator_profile_fingerprint: QualityFingerprint
    claimed_model_profile_fingerprint: QualityFingerprint
    claimed_scorer_fingerprints: dict[str, QualityFingerprint]
    claimed_measurement_profile_fingerprints: dict[str, QualityFingerprint]


class MetricAggregate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metric_id: QualityIdentifier
    unit: MetricUnit
    aggregation: MetricAggregation
    direction: ObjectiveDirection
    value: Annotated[int, Field(ge=0, le=9007199254740991)]


class EligibilityGate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rule_id: QualityIdentifier
    passed: bool
    actual: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    comparator: EligibilityComparator
    threshold: Annotated[int, Field(ge=0, le=9007199254740991)]
    unit: MetricUnit


class EligibilityAssessment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eligible: bool
    total_trial_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    semantic_trial_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    infrastructure_trial_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    semantic_coverage_ppm: Annotated[int, Field(ge=0, le=1000000)]
    infrastructure_failure_ppm: Annotated[int, Field(ge=0, le=1000000)]
    gates: list[EligibilityGate]


class QualityTrialSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fixture_id: QualityIdentifier
    replicate_index: Annotated[int, Field(ge=0, le=65535)]
    provider_attempt_count: Annotated[int, Field(ge=0, le=4294967295)]
    outcome: TrialOutcome
    passed_scorers: list[QualityIdentifier]
    failed_scorers: list[QualityIdentifier]
    observations: list[MetricObservation]


class ParetoFront(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rank: Annotated[int, Field(ge=0, le=4294967295)]
    candidate_fingerprints: list[QualityFingerprint]


class PackageSignature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_id: str
    algorithm: str
    value: str


class FieldSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Annotated[JsonValue, Field(alias='schema')]
    required: bool | None = None
    description: str | None = None


class CapabilityProfileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[str] | None = None


class RenderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inputs: dict[str, JsonValue] | None = None
    context: dict[str, JsonValue] | None = None


class UpdatePackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    version: str | None = None
    description: str | None = None


class CreatePackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    version: str


class SignPackageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_id: str


class VerifyPackageTrustRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    strict: bool | None = False


class CapabilitiesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capabilities: list[str] | None = None


class RunEvalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    contract: str
    fixture_id: str
    capabilities: list[str] | None = None


class DiffContractRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    right_package: str
    right_contract: str


class MigrateLegacyRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    dialect: str
    source: str
    aliases: JsonValue


class RenderDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    template: str
    data: JsonValue
    output: str
    workspace: str | None = None


class InspectDocumentRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    dialect: str
    template: str
    aliases: Annotated[JsonValue | None, Field(validate_default=True)] = Field(
        default_factory=lambda: JsonValue({})
    )


class InspectDocumentResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    report: JsonValue


class ContractSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    id: str
    version: str
    fingerprint: str
    summary: str | None = None
    inputs: list[str] | None = None
    context: list[str] | None = None
    capabilities: list[str] | None = None
    component_count: Annotated[int | None, Field(ge=0)] = None
    components: list[str] | None = None
    unresolved_references: list[str] | None = None
    fix_hints: list[str] | None = None


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: str
    content: str


class CompiledInteraction(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    contract_id: str
    messages: list[Message]
    output_schema: JsonValue
    required_capabilities: list[str]
    runtime_policy: dict[str, JsonValue] | None = None


class AdapterDescriptor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    version: str
    capabilities: list[str]


class StreamEvent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Delta']
    text: str


class StreamEvent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ToolCallDelta']
    name: str
    arguments_fragment: str


class StreamEvent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Failed']
    code: str
    message: str


class Diagnostic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    severity: Severity
    message: str
    file: str | None = None
    json_pointer: str | None = None
    span: SourceSpan | None = None
    help: str | None = None


class TrialEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fixture_id: QualityIdentifier
    replicate_index: Annotated[int, Field(ge=0, le=65535)]
    provider_attempt_count: Annotated[int, Field(ge=1, le=4294967295)]
    outcome: TrialOutcome
    passed_scorers: Annotated[
        list[QualityIdentifier] | None, Field(max_length=16, validate_default=True)
    ] = []
    failed_scorers: Annotated[
        list[QualityIdentifier] | None, Field(max_length=16, validate_default=True)
    ] = []
    observations: Annotated[list[MetricObservation], Field(max_length=16)]


class CandidateAssessment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_fingerprint: QualityFingerprint | None = None
    claimed_identities: Annotated[
        ClaimedQualityIdentities | None,
        Field(
            description='Host-attested identities, omitted unless every returned claim is syntactically valid and consistent with the validated protocol profile.'
        ),
    ] = None
    eligibility: EligibilityAssessment
    aggregates: list[MetricAggregate]
    trial_summaries: list[QualityTrialSummary]
    proposal_change_paths: list[str]
    diagnostics: Annotated[list[Diagnostic], Field(max_length=256)]


class QualityProposalReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    computed_identities: ComputedQualityIdentities
    candidate_assessments: Annotated[list[CandidateAssessment], Field(max_length=32)]
    pareto_fronts: Annotated[list[ParetoFront], Field(max_length=32)]
    report_fingerprint: QualityFingerprint


class PackageManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_version: str
    package: str
    version: str
    description: str | None = None
    contracts: list[str] | None = None
    components: list[str] | None = None
    evals: list[str] | None = None
    migrations: list[str] | None = None
    templates: list[str] | None = None
    provenance: dict[str, str] | None = None
    signatures: list[PackageSignature] | None = None


class Contract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_version: str
    id: str
    version: str
    description: str | None = None
    inputs: dict[str, FieldSpec] | None = None
    context: dict[str, FieldSpec] | None = None
    capabilities: list[str] | None = None
    messages: list[dict[str, Any]]
    output_schema: JsonValue
    runtime_policy: dict[str, JsonValue] | None = None
    extensions: dict[str, JsonValue] | None = None
    components: dict[str, JsonValue] | None = None
    provenance: dict[str, str] | None = None
    evals: list[JsonValue] | None = None


class CompileRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render: RenderRequest | None = None
    capabilities: list[str] | None = None


class ExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    render: RenderRequest | None = None
    capabilities: list[str] | None = None
    fixture_output: JsonValue | None = None
    stream: bool | None = False


class ExecutionReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter: AdapterDescriptor
    request_fingerprint: str
    output_fingerprint: str
    output: JsonValue
    output_schema_valid: bool


class StreamEvent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Complete']
    receipt: ExecutionReceipt


class StreamEvent(RootModel[StreamEvent1 | StreamEvent2 | StreamEvent3 | StreamEvent4]):
    root: StreamEvent1 | StreamEvent2 | StreamEvent3 | StreamEvent4


class OperationEnvelopeBase(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    api_version: Literal['templiqx/v1alpha1']
    operation: str
    ok: bool
    diagnostics: list[Diagnostic]
    fingerprints: dict[str, str]
    stream_events: list[StreamEvent] | None = None


class CatalogEnvelope(OperationEnvelopeBase):
    result: list[str] | None = None


class StringListEnvelope(OperationEnvelopeBase):
    result: list[str] | None = None


class JsonValueEnvelope(OperationEnvelopeBase):
    result: JsonValue | None = None


class PackageListEnvelope(OperationEnvelopeBase):
    result: list[PackageManifest] | None = None


class PackageEnvelope(OperationEnvelopeBase):
    result: PackageManifest | None = None


class ContractEnvelope(OperationEnvelopeBase):
    result: Contract | None = None


class SummaryEnvelope(OperationEnvelopeBase):
    result: ContractSummary | None = None


class CompiledInteractionEnvelope(OperationEnvelopeBase):
    result: CompiledInteraction | None = None


class ExecutionReceiptEnvelope(OperationEnvelopeBase):
    result: ExecutionReceipt | None = None


class InspectDocumentEnvelope(OperationEnvelopeBase):
    result: InspectDocumentResult | None = None


class QualityProposalReportEnvelope(OperationEnvelopeBase):
    result: QualityProposalReport | None = None


class CandidateEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claimed_package_fingerprint: QualityFingerprint
    claimed_base_contract_fingerprint: QualityFingerprint
    claimed_fixture_set_fingerprint: QualityFingerprint
    claimed_candidate_contract_fingerprint: QualityFingerprint
    claimed_quality_policy_fingerprint: QualityFingerprint
    claimed_evaluator_profile_fingerprint: QualityFingerprint
    claimed_model_profile_fingerprint: QualityFingerprint
    claimed_scorer_fingerprints: Annotated[
        dict[str, QualityFingerprint], Field(max_length=16)
    ]
    claimed_measurement_profile_fingerprints: Annotated[
        dict[str, QualityFingerprint], Field(max_length=16)
    ]
    trials: Annotated[list[TrialEvidence], Field(max_length=10240)]


class QualityCandidateSubmission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_source: Annotated[
        str,
        Field(
            description='Complete candidate contract YAML. Templiqx enforces the normative 512 KiB UTF-8 byte limit even when code-point length is smaller.',
            max_length=524288,
        ),
    ]
    synthetic_or_sanitized_data_attestation: bool
    evidence: CandidateEvidence


class QualityProposalRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    package: str
    contract_id: str
    expected_package_fingerprint: QualityFingerprint
    expected_base_contract_fingerprint: QualityFingerprint
    expected_fixture_set_fingerprint: QualityFingerprint
    policy: QualityPolicy
    candidates: Annotated[
        list[QualityCandidateSubmission], Field(max_length=32, min_length=1)
    ]

# Codegen metadata used by the compatibility self-check.
GENERATED_OPENAPI_VERSION = '1.0.0-alpha.2'
GENERATED_OPENAPI_DIGEST = 'sha256:f9aa381dee153007e3298afb7ab85f00ff114dd93a056ea6f54cef7d280432d4'
GENERATED_CONTRACT_FORMAT = 'templiqx/v1alpha1'
GENERATED_ENGINE_API_VERSION = '0.2'
GENERATED_ENGINE_VERSION = '0.2.0'
GENERATED_SDK_VERSION = '0.2.0'
