// Code generated by scripts/generate.go; DO NOT EDIT.

package templiqx

const (
	GeneratedOpenAPIVersion   = "1.0.0-alpha.2"
	GeneratedOpenAPIDigest    = "sha256:f9aa381dee153007e3298afb7ab85f00ff114dd93a056ea6f54cef7d280432d4"
	GeneratedContractFormat   = "templiqx/v1alpha1"
	GeneratedEngineAPIVersion = "0.2"
	GeneratedEngineVersion    = "0.2.0"
	GeneratedSDKVersion       = "0.2.0"
)
