// Code generated by scripts/generate.go; DO NOT EDIT.

package templiqx

const (
	GeneratedOpenAPIVersion   = "1.0.0-alpha.1"
	GeneratedOpenAPIDigest    = "sha256:7cd1c2251d87c27a77efcc35523209d8916cc59d222c8f770b095ecc078a1914"
	GeneratedContractFormat   = "templiqx/v1alpha1"
	GeneratedEngineAPIVersion = "0.1"
	GeneratedEngineVersion    = "0.1.0"
	GeneratedSDKVersion       = "0.1.0"
)
