// Package templiqx provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package templiqx

import (
	"encoding/json"
	"fmt"
)

// Defines values for DiagnosticSeverity.
const (
	Error   DiagnosticSeverity = "error"
	Info    DiagnosticSeverity = "info"
	Warning DiagnosticSeverity = "warning"
)

// Valid indicates whether the value is a known member of the DiagnosticSeverity enum.
func (e DiagnosticSeverity) Valid() bool {
	switch e {
	case Error:
		return true
	case Info:
		return true
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	NotReady HealthStatusStatus = "not_ready"
	Ok       HealthStatusStatus = "ok"
	Ready    HealthStatusStatus = "ready"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ok:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// AdapterDescriptor defines model for AdapterDescriptor.
type AdapterDescriptor struct {
	Capabilities []string `json:"capabilities"`
	Id           string   `json:"id"`
	Version      string   `json:"version"`
}

// CapabilitiesRequest defines model for CapabilitiesRequest.
type CapabilitiesRequest struct {
	Capabilities *[]string `json:"capabilities,omitempty"`
}

// CatalogEnvelope defines model for CatalogEnvelope.
type CatalogEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *[]string              `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CompileRequest defines model for CompileRequest.
type CompileRequest struct {
	Capabilities *[]string      `json:"capabilities,omitempty"`
	Render       *RenderRequest `json:"render,omitempty"`
}

// CompiledInteraction defines model for CompiledInteraction.
type CompiledInteraction struct {
	ContractId string `json:"contract_id"`
	Messages   []struct {
		Content string `json:"content"`
		Role    string `json:"role"`
	} `json:"messages"`

	// OutputSchema Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	OutputSchema         JsonValue              `json:"output_schema"`
	RequiredCapabilities []string               `json:"required_capabilities"`
	RuntimePolicy        *map[string]JsonValue  `json:"runtime_policy,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CompiledInteractionEnvelope defines model for CompiledInteractionEnvelope.
type CompiledInteractionEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *CompiledInteraction   `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Contract defines model for Contract.
type Contract struct {
	ApiVersion   string                   `json:"api_version"`
	Capabilities *[]string                `json:"capabilities,omitempty"`
	Components   *map[string]JsonValue    `json:"components,omitempty"`
	Context      *map[string]FieldSpec    `json:"context,omitempty"`
	Description  *string                  `json:"description,omitempty"`
	Evals        *[]JsonValue             `json:"evals,omitempty"`
	Extensions   *map[string]JsonValue    `json:"extensions,omitempty"`
	Id           string                   `json:"id"`
	Inputs       *map[string]FieldSpec    `json:"inputs,omitempty"`
	Messages     []map[string]interface{} `json:"messages"`

	// OutputSchema Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	OutputSchema  JsonValue             `json:"output_schema"`
	Provenance    *map[string]string    `json:"provenance,omitempty"`
	RuntimePolicy *map[string]JsonValue `json:"runtime_policy,omitempty"`
	Version       string                `json:"version"`
}

// ContractEnvelope defines model for ContractEnvelope.
type ContractEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *Contract              `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ContractSummary defines model for ContractSummary.
type ContractSummary struct {
	Capabilities         *[]string `json:"capabilities,omitempty"`
	ComponentCount       *int      `json:"component_count,omitempty"`
	Components           *[]string `json:"components,omitempty"`
	Context              *[]string `json:"context,omitempty"`
	Fingerprint          string    `json:"fingerprint"`
	FixHints             *[]string `json:"fix_hints,omitempty"`
	Id                   string    `json:"id"`
	Inputs               *[]string `json:"inputs,omitempty"`
	Package              string    `json:"package"`
	Summary              *string   `json:"summary,omitempty"`
	UnresolvedReferences *[]string `json:"unresolved_references,omitempty"`
	Version              string    `json:"version"`
}

// CreatePackageRequest defines model for CreatePackageRequest.
type CreatePackageRequest struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Diagnostic defines model for Diagnostic.
type Diagnostic struct {
	Code        string             `json:"code"`
	File        *string            `json:"file,omitempty"`
	Help        *string            `json:"help,omitempty"`
	JsonPointer *string            `json:"json_pointer,omitempty"`
	Message     string             `json:"message"`
	Severity    DiagnosticSeverity `json:"severity"`
	Span        *SourceSpan        `json:"span,omitempty"`
}

// DiagnosticSeverity defines model for Diagnostic.Severity.
type DiagnosticSeverity string

// DiffContractRequest defines model for DiffContractRequest.
type DiffContractRequest struct {
	RightContract string `json:"right_contract"`
	RightPackage  string `json:"right_package"`
}

// ExecuteRequest defines model for ExecuteRequest.
type ExecuteRequest struct {
	Capabilities *[]string `json:"capabilities,omitempty"`

	// FixtureOutput Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	FixtureOutput *JsonValue     `json:"fixture_output,omitempty"`
	Render        *RenderRequest `json:"render,omitempty"`
	Stream        *bool          `json:"stream,omitempty"`
}

// ExecutionReceipt defines model for ExecutionReceipt.
type ExecutionReceipt struct {
	Adapter AdapterDescriptor `json:"adapter"`

	// Output Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Output             JsonValue `json:"output"`
	OutputFingerprint  string    `json:"output_fingerprint"`
	OutputSchemaValid  bool      `json:"output_schema_valid"`
	RequestFingerprint string    `json:"request_fingerprint"`
}

// ExecutionReceiptEnvelope defines model for ExecutionReceiptEnvelope.
type ExecutionReceiptEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *ExecutionReceipt      `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FieldSpec defines model for FieldSpec.
type FieldSpec struct {
	Description *string `json:"description,omitempty"`
	Required    *bool   `json:"required,omitempty"`

	// Schema Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Schema JsonValue `json:"schema"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	ApiVersion string             `json:"api_version"`
	RequestId  *string            `json:"request_id,omitempty"`
	Status     HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// InspectDocumentEnvelope defines model for InspectDocumentEnvelope.
type InspectDocumentEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *InspectDocumentResult `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// InspectDocumentRequest defines model for InspectDocumentRequest.
type InspectDocumentRequest struct {
	// Aliases Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Aliases  *JsonValue `json:"aliases,omitempty"`
	Dialect  string     `json:"dialect"`
	Package  string     `json:"package"`
	Template string     `json:"template"`
}

// InspectDocumentResult defines model for InspectDocumentResult.
type InspectDocumentResult struct {
	// Report Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Report JsonValue `json:"report"`
}

// JsonValue Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
type JsonValue = interface{}

// JsonValueEnvelope defines model for JsonValueEnvelope.
type JsonValueEnvelope struct {
	ApiVersion   string            `json:"api_version"`
	Diagnostics  []Diagnostic      `json:"diagnostics"`
	Fingerprints map[string]string `json:"fingerprints"`
	Ok           bool              `json:"ok"`
	Operation    string            `json:"operation"`

	// Result Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Result               *JsonValue             `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MigrateLegacyRequest defines model for MigrateLegacyRequest.
type MigrateLegacyRequest struct {
	// Aliases Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Aliases JsonValue `json:"aliases"`
	Dialect string    `json:"dialect"`
	Package string    `json:"package"`
	Source  string    `json:"source"`
}

// OperationEnvelopeBase defines model for OperationEnvelopeBase.
type OperationEnvelopeBase struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PackageEnvelope defines model for PackageEnvelope.
type PackageEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *PackageManifest       `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PackageListEnvelope defines model for PackageListEnvelope.
type PackageListEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *[]PackageManifest     `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PackageManifest defines model for PackageManifest.
type PackageManifest struct {
	ApiVersion  string              `json:"api_version"`
	Components  *[]string           `json:"components,omitempty"`
	Contracts   *[]string           `json:"contracts,omitempty"`
	Description *string             `json:"description,omitempty"`
	Evals       *[]string           `json:"evals,omitempty"`
	Migrations  *[]string           `json:"migrations,omitempty"`
	Package     string              `json:"package"`
	Provenance  *map[string]string  `json:"provenance,omitempty"`
	Signatures  *[]PackageSignature `json:"signatures,omitempty"`
	Templates   *[]string           `json:"templates,omitempty"`
	Version     string              `json:"version"`
}

// PackageSignature defines model for PackageSignature.
type PackageSignature struct {
	Algorithm string `json:"algorithm"`
	KeyId     string `json:"key_id"`
	Value     string `json:"value"`
}

// RenderDocumentRequest defines model for RenderDocumentRequest.
type RenderDocumentRequest struct {
	// Data Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
	Data      JsonValue `json:"data"`
	Output    string    `json:"output"`
	Package   string    `json:"package"`
	Template  string    `json:"template"`
	Workspace *string   `json:"workspace,omitempty"`
}

// RenderRequest defines model for RenderRequest.
type RenderRequest struct {
	Context *map[string]JsonValue `json:"context,omitempty"`
	Inputs  *map[string]JsonValue `json:"inputs,omitempty"`
}

// RunEvalRequest defines model for RunEvalRequest.
type RunEvalRequest struct {
	Capabilities *[]string `json:"capabilities,omitempty"`
	Contract     string    `json:"contract"`
	FixtureId    string    `json:"fixture_id"`
}

// SignPackageRequest defines model for SignPackageRequest.
type SignPackageRequest struct {
	KeyId string `json:"key_id"`
}

// SourceSpan defines model for SourceSpan.
type SourceSpan struct {
	Column    int `json:"column"`
	EndColumn int `json:"end_column"`
	EndLine   int `json:"end_line"`
	Line      int `json:"line"`
}

// StreamEvent defines model for StreamEvent.
type StreamEvent struct {
	union json.RawMessage
}

// StreamEvent0 defines model for .
type StreamEvent0 struct {
	Kind interface{} `json:"kind"`
	Text string      `json:"text"`
}

// StreamEvent1 defines model for .
type StreamEvent1 struct {
	ArgumentsFragment string      `json:"arguments_fragment"`
	Kind              interface{} `json:"kind"`
	Name              string      `json:"name"`
}

// StreamEvent2 defines model for .
type StreamEvent2 struct {
	Code    string      `json:"code"`
	Kind    interface{} `json:"kind"`
	Message string      `json:"message"`
}

// StreamEvent3 defines model for .
type StreamEvent3 struct {
	Kind    interface{}      `json:"kind"`
	Receipt ExecutionReceipt `json:"receipt"`
}

// SummaryEnvelope defines model for SummaryEnvelope.
type SummaryEnvelope struct {
	ApiVersion           string                 `json:"api_version"`
	Diagnostics          []Diagnostic           `json:"diagnostics"`
	Fingerprints         map[string]string      `json:"fingerprints"`
	Ok                   bool                   `json:"ok"`
	Operation            string                 `json:"operation"`
	Result               *ContractSummary       `json:"result,omitempty"`
	StreamEvents         *[]StreamEvent         `json:"stream_events,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TransportError defines model for TransportError.
type TransportError struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"request_id,omitempty"`
}

// UpdatePackageRequest defines model for UpdatePackageRequest.
type UpdatePackageRequest struct {
	Description *string `json:"description,omitempty"`
	Version     *string `json:"version,omitempty"`
}

// VerifyPackageTrustRequest defines model for VerifyPackageTrustRequest.
type VerifyPackageTrustRequest struct {
	Strict *bool `json:"strict,omitempty"`
}

// ArtifactPath defines model for ArtifactPath.
type ArtifactPath = string

// ContractId defines model for ContractId.
type ContractId = string

// IfMatch defines model for IfMatch.
type IfMatch = string

// OptionalIfMatch defines model for OptionalIfMatch.
type OptionalIfMatch = string

// PackageName defines model for PackageName.
type PackageName = string

// PackageQuery defines model for PackageQuery.
type PackageQuery = string

// PrefixQuery defines model for PrefixQuery.
type PrefixQuery = string

// RequestId defines model for RequestId.
type RequestId = string

// TenantId defines model for TenantId.
type TenantId = string

// WorkspaceQuery defines model for WorkspaceQuery.
type WorkspaceQuery = string

// OperationEnvelope defines model for OperationEnvelope.
type OperationEnvelope = JsonValueEnvelope

// TransportFailure defines model for TransportFailure.
type TransportFailure = TransportError

// ListWorkspaceArtifactsParams defines parameters for ListWorkspaceArtifacts.
type ListWorkspaceArtifactsParams struct {
	Package   PackageQuery    `form:"package" json:"package"`
	Workspace *WorkspaceQuery `form:"workspace,omitempty" json:"workspace,omitempty"`
	Prefix    *PrefixQuery    `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// DeleteWorkspaceArtifactParams defines parameters for DeleteWorkspaceArtifact.
type DeleteWorkspaceArtifactParams struct {
	Package   PackageQuery    `form:"package" json:"package"`
	Workspace *WorkspaceQuery `form:"workspace,omitempty" json:"workspace,omitempty"`

	// IfMatch Current content fingerprint required for CAS mutation.
	IfMatch IfMatch `json:"If-Match"`
}

// ReadArtifactParams defines parameters for ReadArtifact.
type ReadArtifactParams struct {
	Package   PackageQuery    `form:"package" json:"package"`
	Workspace *WorkspaceQuery `form:"workspace,omitempty" json:"workspace,omitempty"`
}

// CatalogParams defines parameters for Catalog.
type CatalogParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// DiscoverPackagesParams defines parameters for DiscoverPackages.
type DiscoverPackagesParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// DeletePackageParams defines parameters for DeletePackage.
type DeletePackageParams struct {
	// IfMatch Current content fingerprint required for CAS mutation.
	IfMatch IfMatch `json:"If-Match"`
}

// UpdatePackageParams defines parameters for UpdatePackage.
type UpdatePackageParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`

	// IfMatch Current content fingerprint required for CAS mutation.
	IfMatch IfMatch `json:"If-Match"`
}

// DeleteContractParams defines parameters for DeleteContract.
type DeleteContractParams struct {
	// IfMatch Current content fingerprint required for CAS mutation.
	IfMatch IfMatch `json:"If-Match"`
}

// InspectContractParams defines parameters for InspectContract.
type InspectContractParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// PutContractTextBody defines parameters for PutContract.
type PutContractTextBody = string

// PutContractParams defines parameters for PutContract.
type PutContractParams struct {
	// IfMatch Current content fingerprint when replacing an existing contract.
	IfMatch *OptionalIfMatch `json:"If-Match,omitempty"`
}

// CompileContractParams defines parameters for CompileContract.
type CompileContractParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// ExecuteContractParams defines parameters for ExecuteContract.
type ExecuteContractParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// ValidateContractParams defines parameters for ValidateContract.
type ValidateContractParams struct {
	// XRequestId Caller-provided correlation ID. The transport echoes or generates one.
	XRequestId *RequestId `json:"X-Request-Id,omitempty"`

	// XTenantId Host-owned tenant correlation metadata. Templiqx does not authorize tenants.
	XTenantId *TenantId `json:"X-Tenant-Id,omitempty"`
}

// SignPackageParams defines parameters for SignPackage.
type SignPackageParams struct {
	// IfMatch Current content fingerprint required for CAS mutation.
	IfMatch IfMatch `json:"If-Match"`
}

// InspectDocumentJSONRequestBody defines body for InspectDocument for application/json ContentType.
type InspectDocumentJSONRequestBody = InspectDocumentRequest

// RenderDocumentJSONRequestBody defines body for RenderDocument for application/json ContentType.
type RenderDocumentJSONRequestBody = RenderDocumentRequest

// MigrateLegacyJSONRequestBody defines body for MigrateLegacy for application/json ContentType.
type MigrateLegacyJSONRequestBody = MigrateLegacyRequest

// CreatePackageJSONRequestBody defines body for CreatePackage for application/json ContentType.
type CreatePackageJSONRequestBody = CreatePackageRequest

// UpdatePackageJSONRequestBody defines body for UpdatePackage for application/json ContentType.
type UpdatePackageJSONRequestBody = UpdatePackageRequest

// PutContractTextRequestBody defines body for PutContract for text/plain ContentType.
type PutContractTextRequestBody = PutContractTextBody

// CompileContractJSONRequestBody defines body for CompileContract for application/json ContentType.
type CompileContractJSONRequestBody = CompileRequest

// DiffContractJSONRequestBody defines body for DiffContract for application/json ContentType.
type DiffContractJSONRequestBody = DiffContractRequest

// ExecuteContractJSONRequestBody defines body for ExecuteContract for application/json ContentType.
type ExecuteContractJSONRequestBody = ExecuteRequest

// RenderContractJSONRequestBody defines body for RenderContract for application/json ContentType.
type RenderContractJSONRequestBody = CompileRequest

// RunEvalJSONRequestBody defines body for RunEval for application/json ContentType.
type RunEvalJSONRequestBody = RunEvalRequest

// SignPackageJSONRequestBody defines body for SignPackage for application/json ContentType.
type SignPackageJSONRequestBody = SignPackageRequest

// TestPackageJSONRequestBody defines body for TestPackage for application/json ContentType.
type TestPackageJSONRequestBody = CapabilitiesRequest

// VerifyPackageTrustJSONRequestBody defines body for VerifyPackageTrust for application/json ContentType.
type VerifyPackageTrustJSONRequestBody = VerifyPackageTrustRequest

// Getter for additional properties for CatalogEnvelope. Returns the specified
// element and whether it was found
func (a CatalogEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CatalogEnvelope
func (a *CatalogEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CatalogEnvelope to handle AdditionalProperties
func (a *CatalogEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CatalogEnvelope to handle AdditionalProperties
func (a CatalogEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CompiledInteraction. Returns the specified
// element and whether it was found
func (a CompiledInteraction) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CompiledInteraction
func (a *CompiledInteraction) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CompiledInteraction to handle AdditionalProperties
func (a *CompiledInteraction) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["contract_id"]; found {
		err = json.Unmarshal(raw, &a.ContractId)
		if err != nil {
			return fmt.Errorf("error reading 'contract_id': %w", err)
		}
		delete(object, "contract_id")
	}

	if raw, found := object["messages"]; found {
		err = json.Unmarshal(raw, &a.Messages)
		if err != nil {
			return fmt.Errorf("error reading 'messages': %w", err)
		}
		delete(object, "messages")
	}

	if raw, found := object["output_schema"]; found {
		err = json.Unmarshal(raw, &a.OutputSchema)
		if err != nil {
			return fmt.Errorf("error reading 'output_schema': %w", err)
		}
		delete(object, "output_schema")
	}

	if raw, found := object["required_capabilities"]; found {
		err = json.Unmarshal(raw, &a.RequiredCapabilities)
		if err != nil {
			return fmt.Errorf("error reading 'required_capabilities': %w", err)
		}
		delete(object, "required_capabilities")
	}

	if raw, found := object["runtime_policy"]; found {
		err = json.Unmarshal(raw, &a.RuntimePolicy)
		if err != nil {
			return fmt.Errorf("error reading 'runtime_policy': %w", err)
		}
		delete(object, "runtime_policy")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CompiledInteraction to handle AdditionalProperties
func (a CompiledInteraction) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["contract_id"], err = json.Marshal(a.ContractId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'contract_id': %w", err)
	}

	if a.Messages != nil {
		object["messages"], err = json.Marshal(a.Messages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'messages': %w", err)
		}
	}

	object["output_schema"], err = json.Marshal(a.OutputSchema)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'output_schema': %w", err)
	}

	if a.RequiredCapabilities != nil {
		object["required_capabilities"], err = json.Marshal(a.RequiredCapabilities)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'required_capabilities': %w", err)
		}
	}

	if a.RuntimePolicy != nil {
		object["runtime_policy"], err = json.Marshal(a.RuntimePolicy)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'runtime_policy': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CompiledInteractionEnvelope. Returns the specified
// element and whether it was found
func (a CompiledInteractionEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CompiledInteractionEnvelope
func (a *CompiledInteractionEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CompiledInteractionEnvelope to handle AdditionalProperties
func (a *CompiledInteractionEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CompiledInteractionEnvelope to handle AdditionalProperties
func (a CompiledInteractionEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ContractEnvelope. Returns the specified
// element and whether it was found
func (a ContractEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ContractEnvelope
func (a *ContractEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ContractEnvelope to handle AdditionalProperties
func (a *ContractEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ContractEnvelope to handle AdditionalProperties
func (a ContractEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExecutionReceiptEnvelope. Returns the specified
// element and whether it was found
func (a ExecutionReceiptEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExecutionReceiptEnvelope
func (a *ExecutionReceiptEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExecutionReceiptEnvelope to handle AdditionalProperties
func (a *ExecutionReceiptEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExecutionReceiptEnvelope to handle AdditionalProperties
func (a ExecutionReceiptEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for InspectDocumentEnvelope. Returns the specified
// element and whether it was found
func (a InspectDocumentEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InspectDocumentEnvelope
func (a *InspectDocumentEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InspectDocumentEnvelope to handle AdditionalProperties
func (a *InspectDocumentEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InspectDocumentEnvelope to handle AdditionalProperties
func (a InspectDocumentEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for JsonValueEnvelope. Returns the specified
// element and whether it was found
func (a JsonValueEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for JsonValueEnvelope
func (a *JsonValueEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for JsonValueEnvelope to handle AdditionalProperties
func (a *JsonValueEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for JsonValueEnvelope to handle AdditionalProperties
func (a JsonValueEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for OperationEnvelopeBase. Returns the specified
// element and whether it was found
func (a OperationEnvelopeBase) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OperationEnvelopeBase
func (a *OperationEnvelopeBase) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OperationEnvelopeBase to handle AdditionalProperties
func (a *OperationEnvelopeBase) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OperationEnvelopeBase to handle AdditionalProperties
func (a OperationEnvelopeBase) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PackageEnvelope. Returns the specified
// element and whether it was found
func (a PackageEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PackageEnvelope
func (a *PackageEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PackageEnvelope to handle AdditionalProperties
func (a *PackageEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PackageEnvelope to handle AdditionalProperties
func (a PackageEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PackageListEnvelope. Returns the specified
// element and whether it was found
func (a PackageListEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PackageListEnvelope
func (a *PackageListEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PackageListEnvelope to handle AdditionalProperties
func (a *PackageListEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PackageListEnvelope to handle AdditionalProperties
func (a PackageListEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SummaryEnvelope. Returns the specified
// element and whether it was found
func (a SummaryEnvelope) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SummaryEnvelope
func (a *SummaryEnvelope) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SummaryEnvelope to handle AdditionalProperties
func (a *SummaryEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["api_version"]; found {
		err = json.Unmarshal(raw, &a.ApiVersion)
		if err != nil {
			return fmt.Errorf("error reading 'api_version': %w", err)
		}
		delete(object, "api_version")
	}

	if raw, found := object["diagnostics"]; found {
		err = json.Unmarshal(raw, &a.Diagnostics)
		if err != nil {
			return fmt.Errorf("error reading 'diagnostics': %w", err)
		}
		delete(object, "diagnostics")
	}

	if raw, found := object["fingerprints"]; found {
		err = json.Unmarshal(raw, &a.Fingerprints)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprints': %w", err)
		}
		delete(object, "fingerprints")
	}

	if raw, found := object["ok"]; found {
		err = json.Unmarshal(raw, &a.Ok)
		if err != nil {
			return fmt.Errorf("error reading 'ok': %w", err)
		}
		delete(object, "ok")
	}

	if raw, found := object["operation"]; found {
		err = json.Unmarshal(raw, &a.Operation)
		if err != nil {
			return fmt.Errorf("error reading 'operation': %w", err)
		}
		delete(object, "operation")
	}

	if raw, found := object["result"]; found {
		err = json.Unmarshal(raw, &a.Result)
		if err != nil {
			return fmt.Errorf("error reading 'result': %w", err)
		}
		delete(object, "result")
	}

	if raw, found := object["stream_events"]; found {
		err = json.Unmarshal(raw, &a.StreamEvents)
		if err != nil {
			return fmt.Errorf("error reading 'stream_events': %w", err)
		}
		delete(object, "stream_events")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SummaryEnvelope to handle AdditionalProperties
func (a SummaryEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["api_version"], err = json.Marshal(a.ApiVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'api_version': %w", err)
	}

	if a.Diagnostics != nil {
		object["diagnostics"], err = json.Marshal(a.Diagnostics)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'diagnostics': %w", err)
		}
	}

	if a.Fingerprints != nil {
		object["fingerprints"], err = json.Marshal(a.Fingerprints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprints': %w", err)
		}
	}

	object["ok"], err = json.Marshal(a.Ok)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'ok': %w", err)
	}

	object["operation"], err = json.Marshal(a.Operation)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'operation': %w", err)
	}

	if a.Result != nil {
		object["result"], err = json.Marshal(a.Result)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'result': %w", err)
		}
	}

	if a.StreamEvents != nil {
		object["stream_events"], err = json.Marshal(a.StreamEvents)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream_events': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsStreamEvent0 returns the union data inside the StreamEvent as a StreamEvent0
func (t StreamEvent) AsStreamEvent0() (StreamEvent0, error) {
	var body StreamEvent0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamEvent0 overwrites any union data inside the StreamEvent as the provided StreamEvent0
func (t *StreamEvent) FromStreamEvent0(v StreamEvent0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamEvent0 performs a merge with any union data inside the StreamEvent, using the provided StreamEvent0
func (t *StreamEvent) MergeStreamEvent0(v StreamEvent0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := generatedJSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamEvent1 returns the union data inside the StreamEvent as a StreamEvent1
func (t StreamEvent) AsStreamEvent1() (StreamEvent1, error) {
	var body StreamEvent1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamEvent1 overwrites any union data inside the StreamEvent as the provided StreamEvent1
func (t *StreamEvent) FromStreamEvent1(v StreamEvent1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamEvent1 performs a merge with any union data inside the StreamEvent, using the provided StreamEvent1
func (t *StreamEvent) MergeStreamEvent1(v StreamEvent1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := generatedJSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamEvent2 returns the union data inside the StreamEvent as a StreamEvent2
func (t StreamEvent) AsStreamEvent2() (StreamEvent2, error) {
	var body StreamEvent2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamEvent2 overwrites any union data inside the StreamEvent as the provided StreamEvent2
func (t *StreamEvent) FromStreamEvent2(v StreamEvent2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamEvent2 performs a merge with any union data inside the StreamEvent, using the provided StreamEvent2
func (t *StreamEvent) MergeStreamEvent2(v StreamEvent2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := generatedJSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamEvent3 returns the union data inside the StreamEvent as a StreamEvent3
func (t StreamEvent) AsStreamEvent3() (StreamEvent3, error) {
	var body StreamEvent3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamEvent3 overwrites any union data inside the StreamEvent as the provided StreamEvent3
func (t *StreamEvent) FromStreamEvent3(v StreamEvent3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamEvent3 performs a merge with any union data inside the StreamEvent, using the provided StreamEvent3
func (t *StreamEvent) MergeStreamEvent3(v StreamEvent3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := generatedJSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StreamEvent) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StreamEvent) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// generatedJSONMerge supports union DTO serialization without a runtime dependency.
func generatedJSONMerge(values ...[]byte) ([]byte, error) {
	merged := make(map[string]json.RawMessage)
	for _, value := range values {
		if len(value) == 0 || string(value) == "null" {
			continue
		}
		var object map[string]json.RawMessage
		if err := json.Unmarshal(value, &object); err != nil {
			return nil, err
		}
		for key, field := range object {
			merged[key] = field
		}
	}
	return json.Marshal(merged)
}
