//go:build ignore

// Command generate reproducibly creates the checked-in Operations API DTOs and
// compatibility constants. Run it from any directory with `go run scripts/generate.go`.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

const generator = "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.7.2"

var (
	scalarPattern = func(name string) *regexp.Regexp {
		return regexp.MustCompile(`(?m)^\s*` + regexp.QuoteMeta(name) + `:\s*"?([^"\r\n]+?)"?\s*$`)
	}
)

func main() {
	check := flag.Bool("check", false, "fail when checked-in generated files differ")
	flag.Parse()
	if flag.NArg() != 0 {
		fatalf("unexpected arguments: %s", strings.Join(flag.Args(), " "))
	}

	_, source, _, ok := runtime.Caller(0)
	if !ok {
		fatalf("could not locate generator source")
	}
	packageRoot := filepath.Dir(filepath.Dir(source))
	repoRoot := filepath.Dir(filepath.Dir(packageRoot))
	specPath := filepath.Join(repoRoot, "openapi", "templiqx-operations-v1.yaml")
	matrixPath := filepath.Join(repoRoot, "openapi", "compatibility-matrix.yaml")
	modPath := filepath.Join(packageRoot, "go.mod")
	dtoPath := filepath.Join(packageRoot, "operations_v1.gen.go")
	compatPath := filepath.Join(packageRoot, "compat_generated.go")

	spec := mustRead(specPath)
	matrix := mustRead(matrixPath)
	manifest := mustRead(modPath)
	metadata := readMetadata(spec, matrix, manifest)

	tempDir, err := os.MkdirTemp("", "templiqx-go-sdk-")
	if err != nil {
		fatalf("create temporary directory: %v", err)
	}
	defer os.RemoveAll(tempDir)
	tempDTO := filepath.Join(tempDir, "operations_v1.gen.go")

	cmd := exec.Command(
		"go", "run", generator,
		"-generate", "types",
		"-package", "templiqx",
		"-o", tempDTO,
		specPath,
	)
	cmd.Dir = packageRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fatalf("oapi-codegen failed: %v", err)
	}

	dto := mustRead(tempDTO)
	runtimeImport := []byte("\n\t\"github.com/oapi-codegen/runtime\"\n")
	if count := bytes.Count(dto, runtimeImport); count != 1 {
		fatalf("expected exactly one generated runtime import, got %d", count)
	}
	if count := bytes.Count(dto, []byte("runtime.JSONMerge")); count != 4 {
		fatalf("expected exactly four generated runtime.JSONMerge calls, got %d", count)
	}
	dto = bytes.Replace(dto, runtimeImport, nil, 1)
	dto = bytes.ReplaceAll(dto, []byte("runtime.JSONMerge"), []byte("generatedJSONMerge"))
	dto = append(dto, []byte(`
// generatedJSONMerge supports union DTO serialization without a runtime dependency.
func generatedJSONMerge(values ...[]byte) ([]byte, error) {
	merged := make(map[string]json.RawMessage)
	for _, value := range values {
		if len(value) == 0 || string(value) == "null" {
			continue
		}
		var object map[string]json.RawMessage
		if err := json.Unmarshal(value, &object); err != nil {
			return nil, err
		}
		for key, field := range object {
			merged[key] = field
		}
	}
	return json.Marshal(merged)
}
`)...)
	dto, err = format.Source(dto)
	if err != nil {
		fatalf("format generated DTOs: %v", err)
	}

	compat := []byte(fmt.Sprintf(`// Code generated by scripts/generate.go; DO NOT EDIT.

package templiqx

const (
	GeneratedOpenAPIVersion   = %q
	GeneratedOpenAPIDigest    = %q
	GeneratedContractFormat   = %q
	GeneratedEngineAPIVersion = %q
	GeneratedEngineVersion    = %q
	GeneratedSDKVersion       = %q
)
`, metadata.opsAPIVersion, metadata.digest, metadata.contractFormat,
		metadata.engineAPIVersion, metadata.engineVersion, metadata.sdkVersion))
	compat, err = format.Source(compat)
	if err != nil {
		fatalf("format generated compatibility metadata: %v", err)
	}

	if *check {
		current(dtoPath, dto, "Go DTOs")
		current(compatPath, compat, "Go compatibility metadata")
		return
	}
	mustWrite(dtoPath, dto)
	mustWrite(compatPath, compat)
	fmt.Printf("Generated Go DTOs: %s\n", dtoPath)
	fmt.Printf("Generated Go compatibility metadata: %s\n", compatPath)
}

type metadata struct {
	opsAPIVersion, digest, contractFormat, engineAPIVersion, engineVersion, sdkVersion string
}

func readMetadata(spec, matrix, manifest []byte) metadata {
	versionMatch := regexp.MustCompile(`(?m)^  version:\s*([^\s#]+)\s*$`).FindSubmatch(spec)
	if versionMatch == nil {
		fatalf("OpenAPI info.version is missing")
	}
	field := func(source []byte, name string) string {
		match := scalarPattern(name).FindSubmatch(source)
		if match == nil {
			fatalf("compatibility field %s is missing", name)
		}
		return string(match[1])
	}
	manifestVersion := regexp.MustCompile(`(?m)^// templiqx-sdk-version:\s*(\S+)\s*$`).FindSubmatch(manifest)
	if manifestVersion == nil {
		fatalf("go.mod SDK version marker is missing")
	}
	sdkVersion := string(manifestVersion[1])
	digest := fmt.Sprintf("sha256:%x", sha256.Sum256(spec))
	if expected := field(matrix, "openApiDigest"); expected != digest {
		fatalf("compatibility digest %s does not match OpenAPI digest %s", expected, digest)
	}
	return metadata{
		opsAPIVersion:    string(versionMatch[1]),
		digest:           digest,
		contractFormat:   field(matrix, "contractFormat"),
		engineAPIVersion: field(matrix, "engineApiVersion"),
		engineVersion:    field(matrix, "engineVersion"),
		sdkVersion:       sdkVersion,
	}
}

func current(path string, expected []byte, label string) {
	actual, err := os.ReadFile(path)
	if err != nil || !bytes.Equal(actual, expected) {
		fmt.Fprintf(os.Stderr, "Generated %s are stale: %s\n", label, path)
		os.Exit(1)
	}
	fmt.Printf("Generated %s are current: %s\n", label, path)
}

func mustRead(path string) []byte {
	contents, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	return contents
}

func mustWrite(path string, contents []byte) {
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
