// @generated by `scripts/generate.sh` from openapi/templiqx-operations-v1.yaml.
// Do not edit by hand.

/// Error types.
pub mod error {
    /// Error from a `TryFrom` or `FromStr` implementation.
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
///`AdapterDescriptor`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "capabilities",
///    "id",
///    "version"
///  ],
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "id": {
///      "type": "string"
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct AdapterDescriptor {
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    pub id: ::std::string::String,
    pub version: ::std::string::String,
}
///`CapabilitiesRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CapabilitiesRequest {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
}
impl ::std::default::Default for CapabilitiesRequest {
    fn default() -> Self {
        Self {
            capabilities: Default::default(),
        }
    }
}
///`CapabilityProfileRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CapabilityProfileRequest {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
}
impl ::std::default::Default for CapabilityProfileRequest {
    fn default() -> Self {
        Self {
            capabilities: Default::default(),
        }
    }
}
///`CatalogEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "type": "array",
///          "items": {
///            "type": "string"
///          }
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CatalogEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub result: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`CompileRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "render": {
///      "$ref": "#/definitions/RenderRequest"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CompileRequest {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub render: ::std::option::Option<RenderRequest>,
}
impl ::std::default::Default for CompileRequest {
    fn default() -> Self {
        Self {
            capabilities: Default::default(),
            render: Default::default(),
        }
    }
}
///`CompiledInteraction`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "contract_id",
///    "messages",
///    "output_schema",
///    "required_capabilities"
///  ],
///  "properties": {
///    "contract_id": {
///      "type": "string"
///    },
///    "messages": {
///      "type": "array",
///      "items": {
///        "type": "object",
///        "required": [
///          "content",
///          "role"
///        ],
///        "properties": {
///          "content": {
///            "type": "string"
///          },
///          "role": {
///            "type": "string"
///          }
///        },
///        "additionalProperties": false
///      }
///    },
///    "output_schema": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "required_capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "runtime_policy": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    }
///  },
///  "additionalProperties": true
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CompiledInteraction {
    pub contract_id: ::std::string::String,
    pub messages: ::std::vec::Vec<CompiledInteractionMessagesItem>,
    pub output_schema: JsonValue,
    pub required_capabilities: ::std::vec::Vec<::std::string::String>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub runtime_policy: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
}
///`CompiledInteractionEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/CompiledInteraction"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct CompiledInteractionEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<CompiledInteraction>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`CompiledInteractionMessagesItem`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "content",
///    "role"
///  ],
///  "properties": {
///    "content": {
///      "type": "string"
///    },
///    "role": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CompiledInteractionMessagesItem {
    pub content: ::std::string::String,
    pub role: ::std::string::String,
}
///`Contract`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "api_version",
///    "id",
///    "messages",
///    "output_schema",
///    "version"
///  ],
///  "properties": {
///    "api_version": {
///      "type": "string"
///    },
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "components": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    },
///    "context": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/FieldSpec"
///      }
///    },
///    "description": {
///      "type": "string"
///    },
///    "evals": {
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    },
///    "extensions": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    },
///    "id": {
///      "type": "string"
///    },
///    "inputs": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/FieldSpec"
///      }
///    },
///    "messages": {
///      "type": "array",
///      "items": {
///        "type": "object",
///        "additionalProperties": true
///      }
///    },
///    "output_schema": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "provenance": {
///      "type": "object",
///      "additionalProperties": {
///        "type": "string"
///      }
///    },
///    "runtime_policy": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Contract {
    pub api_version: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub components: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub context: ::std::collections::BTreeMap<::std::string::String, FieldSpec>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub evals: ::std::vec::Vec<JsonValue>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub extensions: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
    pub id: ::std::string::String,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub inputs: ::std::collections::BTreeMap<::std::string::String, FieldSpec>,
    pub messages: ::std::vec::Vec<::serde_json::Map<::std::string::String, ::serde_json::Value>>,
    pub output_schema: JsonValue,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub provenance: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub runtime_policy: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
    pub version: ::std::string::String,
}
///`ContractEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/Contract"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ContractEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<Contract>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`ContractSummary`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "fingerprint",
///    "id",
///    "package",
///    "version"
///  ],
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "component_count": {
///      "type": "integer",
///      "minimum": 0.0
///    },
///    "components": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "context": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "fingerprint": {
///      "type": "string"
///    },
///    "fix_hints": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "id": {
///      "type": "string"
///    },
///    "inputs": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "package": {
///      "type": "string"
///    },
///    "summary": {
///      "type": "string"
///    },
///    "unresolved_references": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ContractSummary {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub component_count: ::std::option::Option<u64>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub components: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub context: ::std::vec::Vec<::std::string::String>,
    pub fingerprint: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub fix_hints: ::std::vec::Vec<::std::string::String>,
    pub id: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub inputs: ::std::vec::Vec<::std::string::String>,
    pub package: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub summary: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub unresolved_references: ::std::vec::Vec<::std::string::String>,
    pub version: ::std::string::String,
}
///`CreatePackageRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "name",
///    "version"
///  ],
///  "properties": {
///    "name": {
///      "type": "string"
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct CreatePackageRequest {
    pub name: ::std::string::String,
    pub version: ::std::string::String,
}
///`Diagnostic`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "code",
///    "message",
///    "severity"
///  ],
///  "properties": {
///    "code": {
///      "type": "string"
///    },
///    "file": {
///      "type": "string"
///    },
///    "help": {
///      "type": "string"
///    },
///    "json_pointer": {
///      "type": "string"
///    },
///    "message": {
///      "type": "string"
///    },
///    "severity": {
///      "type": "string",
///      "enum": [
///        "error",
///        "warning",
///        "info"
///      ]
///    },
///    "span": {
///      "$ref": "#/definitions/SourceSpan"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct Diagnostic {
    pub code: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub file: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub help: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub json_pointer: ::std::option::Option<::std::string::String>,
    pub message: ::std::string::String,
    pub severity: DiagnosticSeverity,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub span: ::std::option::Option<SourceSpan>,
}
///`DiagnosticSeverity`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "error",
///    "warning",
///    "info"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum DiagnosticSeverity {
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "info")]
    Info,
}
impl ::std::fmt::Display for DiagnosticSeverity {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Error => f.write_str("error"),
            Self::Warning => f.write_str("warning"),
            Self::Info => f.write_str("info"),
        }
    }
}
impl ::std::str::FromStr for DiagnosticSeverity {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "error" => Ok(Self::Error),
            "warning" => Ok(Self::Warning),
            "info" => Ok(Self::Info),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for DiagnosticSeverity {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for DiagnosticSeverity {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for DiagnosticSeverity {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`DiffContractRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "right_contract",
///    "right_package"
///  ],
///  "properties": {
///    "right_contract": {
///      "type": "string"
///    },
///    "right_package": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct DiffContractRequest {
    pub right_contract: ::std::string::String,
    pub right_package: ::std::string::String,
}
///`ExecuteRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "fixture_output": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "render": {
///      "$ref": "#/definitions/RenderRequest"
///    },
///    "stream": {
///      "default": false,
///      "type": "boolean"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ExecuteRequest {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub fixture_output: ::std::option::Option<JsonValue>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub render: ::std::option::Option<RenderRequest>,
    #[serde(default)]
    pub stream: bool,
}
impl ::std::default::Default for ExecuteRequest {
    fn default() -> Self {
        Self {
            capabilities: Default::default(),
            fixture_output: Default::default(),
            render: Default::default(),
            stream: Default::default(),
        }
    }
}
///`ExecutionReceipt`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "adapter",
///    "output",
///    "output_fingerprint",
///    "output_schema_valid",
///    "request_fingerprint"
///  ],
///  "properties": {
///    "adapter": {
///      "$ref": "#/definitions/AdapterDescriptor"
///    },
///    "output": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "output_fingerprint": {
///      "type": "string"
///    },
///    "output_schema_valid": {
///      "type": "boolean"
///    },
///    "request_fingerprint": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct ExecutionReceipt {
    pub adapter: AdapterDescriptor,
    pub output: JsonValue,
    pub output_fingerprint: ::std::string::String,
    pub output_schema_valid: bool,
    pub request_fingerprint: ::std::string::String,
}
///`ExecutionReceiptEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/ExecutionReceipt"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct ExecutionReceiptEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<ExecutionReceipt>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`FieldSpec`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "schema"
///  ],
///  "properties": {
///    "description": {
///      "type": "string"
///    },
///    "required": {
///      "type": "boolean"
///    },
///    "schema": {
///      "$ref": "#/definitions/JsonValue"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct FieldSpec {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub required: ::std::option::Option<bool>,
    pub schema: JsonValue,
}
///`HealthStatus`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "api_version",
///    "status"
///  ],
///  "properties": {
///    "api_version": {
///      "type": "string"
///    },
///    "request_id": {
///      "type": "string"
///    },
///    "status": {
///      "type": "string",
///      "enum": [
///        "ok",
///        "ready",
///        "not_ready"
///      ]
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct HealthStatus {
    pub api_version: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub request_id: ::std::option::Option<::std::string::String>,
    pub status: HealthStatusStatus,
}
///`HealthStatusStatus`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "string",
///  "enum": [
///    "ok",
///    "ready",
///    "not_ready"
///  ]
///}
/// ```
/// </details>
#[derive(
    ::serde::Deserialize,
    ::serde::Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum HealthStatusStatus {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "not_ready")]
    NotReady,
}
impl ::std::fmt::Display for HealthStatusStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Ok => f.write_str("ok"),
            Self::Ready => f.write_str("ready"),
            Self::NotReady => f.write_str("not_ready"),
        }
    }
}
impl ::std::str::FromStr for HealthStatusStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "ok" => Ok(Self::Ok),
            "ready" => Ok(Self::Ready),
            "not_ready" => Ok(Self::NotReady),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for HealthStatusStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for HealthStatusStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for HealthStatusStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
///`InspectDocumentEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/InspectDocumentResult"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct InspectDocumentEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<InspectDocumentResult>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`InspectDocumentRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "dialect",
///    "package",
///    "template"
///  ],
///  "properties": {
///    "aliases": {
///      "default": {},
///      "$ref": "#/definitions/JsonValue"
///    },
///    "dialect": {
///      "type": "string"
///    },
///    "package": {
///      "type": "string"
///    },
///    "template": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct InspectDocumentRequest {
    #[serde(default = "defaults::inspect_document_request_aliases")]
    pub aliases: JsonValue,
    pub dialect: ::std::string::String,
    pub package: ::std::string::String,
    pub template: ::std::string::String,
}
///`InspectDocumentResult`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "report"
///  ],
///  "properties": {
///    "report": {
///      "$ref": "#/definitions/JsonValue"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct InspectDocumentResult {
    pub report: JsonValue,
}
///Arbitrary JSON value owned by Templiqx contract schemas or runtime output.
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "description": "Arbitrary JSON value owned by Templiqx contract schemas or runtime output."
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct JsonValue(pub ::serde_json::Value);
impl ::std::ops::Deref for JsonValue {
    type Target = ::serde_json::Value;
    fn deref(&self) -> &::serde_json::Value {
        &self.0
    }
}
impl ::std::convert::From<JsonValue> for ::serde_json::Value {
    fn from(value: JsonValue) -> Self {
        value.0
    }
}
impl ::std::convert::From<::serde_json::Value> for JsonValue {
    fn from(value: ::serde_json::Value) -> Self {
        Self(value)
    }
}
///`JsonValueEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/JsonValue"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct JsonValueEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<JsonValue>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`MigrateLegacyRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "aliases",
///    "dialect",
///    "package",
///    "source"
///  ],
///  "properties": {
///    "aliases": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "dialect": {
///      "type": "string"
///    },
///    "package": {
///      "type": "string"
///    },
///    "source": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct MigrateLegacyRequest {
    pub aliases: JsonValue,
    pub dialect: ::std::string::String,
    pub package: ::std::string::String,
    pub source: ::std::string::String,
}
///`OperationEnvelopeBase`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "api_version",
///    "diagnostics",
///    "fingerprints",
///    "ok",
///    "operation"
///  ],
///  "properties": {
///    "api_version": {
///      "type": "string",
///      "const": "templiqx/v1alpha1"
///    },
///    "diagnostics": {
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/Diagnostic"
///      }
///    },
///    "fingerprints": {
///      "type": "object",
///      "additionalProperties": {
///        "type": "string"
///      }
///    },
///    "ok": {
///      "type": "boolean"
///    },
///    "operation": {
///      "type": "string"
///    },
///    "stream_events": {
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/StreamEvent"
///      }
///    }
///  },
///  "additionalProperties": true
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct OperationEnvelopeBase {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`PackageEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/PackageManifest"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct PackageEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<PackageManifest>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`PackageListEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "type": "array",
///          "items": {
///            "$ref": "#/definitions/PackageManifest"
///          }
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct PackageListEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub result: ::std::vec::Vec<PackageManifest>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`PackageManifest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "api_version",
///    "package",
///    "version"
///  ],
///  "properties": {
///    "api_version": {
///      "type": "string"
///    },
///    "components": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "contracts": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "description": {
///      "type": "string"
///    },
///    "evals": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "migrations": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "package": {
///      "type": "string"
///    },
///    "provenance": {
///      "type": "object",
///      "additionalProperties": {
///        "type": "string"
///      }
///    },
///    "signatures": {
///      "type": "array",
///      "items": {
///        "$ref": "#/definitions/PackageSignature"
///      }
///    },
///    "templates": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PackageManifest {
    pub api_version: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub components: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub contracts: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub evals: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub migrations: ::std::vec::Vec<::std::string::String>,
    pub package: ::std::string::String,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub provenance: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub signatures: ::std::vec::Vec<PackageSignature>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub templates: ::std::vec::Vec<::std::string::String>,
    pub version: ::std::string::String,
}
///`PackageSignature`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "algorithm",
///    "key_id",
///    "value"
///  ],
///  "properties": {
///    "algorithm": {
///      "type": "string"
///    },
///    "key_id": {
///      "type": "string"
///    },
///    "value": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct PackageSignature {
    pub algorithm: ::std::string::String,
    pub key_id: ::std::string::String,
    pub value: ::std::string::String,
}
///`RenderDocumentRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "data",
///    "output",
///    "package",
///    "template"
///  ],
///  "properties": {
///    "data": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "output": {
///      "type": "string"
///    },
///    "package": {
///      "type": "string"
///    },
///    "template": {
///      "type": "string"
///    },
///    "workspace": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RenderDocumentRequest {
    pub data: JsonValue,
    pub output: ::std::string::String,
    pub package: ::std::string::String,
    pub template: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub workspace: ::std::option::Option<::std::string::String>,
}
///`RenderRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "context": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    },
///    "inputs": {
///      "type": "object",
///      "additionalProperties": {
///        "$ref": "#/definitions/JsonValue"
///      }
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RenderRequest {
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub context: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: BTreeMap::is_empty"
    )]
    pub inputs: ::std::collections::BTreeMap<::std::string::String, JsonValue>,
}
impl ::std::default::Default for RenderRequest {
    fn default() -> Self {
        Self {
            context: Default::default(),
            inputs: Default::default(),
        }
    }
}
///`RunEvalRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "contract",
///    "fixture_id"
///  ],
///  "properties": {
///    "capabilities": {
///      "type": "array",
///      "items": {
///        "type": "string"
///      }
///    },
///    "contract": {
///      "type": "string"
///    },
///    "fixture_id": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct RunEvalRequest {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub capabilities: ::std::vec::Vec<::std::string::String>,
    pub contract: ::std::string::String,
    pub fixture_id: ::std::string::String,
}
///`SignPackageRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "key_id"
///  ],
///  "properties": {
///    "key_id": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct SignPackageRequest {
    pub key_id: ::std::string::String,
}
///`SourceSpan`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "column",
///    "end_column",
///    "end_line",
///    "line"
///  ],
///  "properties": {
///    "column": {
///      "type": "integer",
///      "minimum": 0.0
///    },
///    "end_column": {
///      "type": "integer",
///      "minimum": 0.0
///    },
///    "end_line": {
///      "type": "integer",
///      "minimum": 0.0
///    },
///    "line": {
///      "type": "integer",
///      "minimum": 0.0
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct SourceSpan {
    pub column: u64,
    pub end_column: u64,
    pub end_line: u64,
    pub line: u64,
}
///`StreamEvent`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "oneOf": [
///    {
///      "type": "object",
///      "required": [
///        "kind",
///        "text"
///      ],
///      "properties": {
///        "kind": {
///          "const": "Delta"
///        },
///        "text": {
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "type": "object",
///      "required": [
///        "arguments_fragment",
///        "kind",
///        "name"
///      ],
///      "properties": {
///        "arguments_fragment": {
///          "type": "string"
///        },
///        "kind": {
///          "const": "ToolCallDelta"
///        },
///        "name": {
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "type": "object",
///      "required": [
///        "code",
///        "kind",
///        "message"
///      ],
///      "properties": {
///        "code": {
///          "type": "string"
///        },
///        "kind": {
///          "const": "Failed"
///        },
///        "message": {
///          "type": "string"
///        }
///      },
///      "additionalProperties": false
///    },
///    {
///      "type": "object",
///      "required": [
///        "kind",
///        "receipt"
///      ],
///      "properties": {
///        "kind": {
///          "const": "Complete"
///        },
///        "receipt": {
///          "$ref": "#/definitions/ExecutionReceipt"
///        }
///      },
///      "additionalProperties": false
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(tag = "kind", deny_unknown_fields)]
pub enum StreamEvent {
    Delta {
        text: ::std::string::String,
    },
    ToolCallDelta {
        arguments_fragment: ::std::string::String,
        name: ::std::string::String,
    },
    Failed {
        code: ::std::string::String,
        message: ::std::string::String,
    },
    Complete {
        receipt: ExecutionReceipt,
    },
}
///`StringListEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "type": "array",
///          "items": {
///            "type": "string"
///          }
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct StringListEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub result: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`SummaryEnvelope`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "allOf": [
///    {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    {
///      "type": "object",
///      "properties": {
///        "result": {
///          "$ref": "#/definitions/ContractSummary"
///        }
///      }
///    }
///  ]
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct SummaryEnvelope {
    pub api_version: ::std::string::String,
    pub diagnostics: ::std::vec::Vec<Diagnostic>,
    pub fingerprints: ::std::collections::BTreeMap<::std::string::String, ::std::string::String>,
    pub ok: bool,
    pub operation: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub result: ::std::option::Option<ContractSummary>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub stream_events: ::std::vec::Vec<StreamEvent>,
}
///`TempliqxOperationsV1`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "title": "TempliqxOperationsV1",
///  "type": "object",
///  "properties": {
///    "AdapterDescriptor": {
///      "$ref": "#/definitions/AdapterDescriptor"
///    },
///    "CapabilitiesRequest": {
///      "$ref": "#/definitions/CapabilitiesRequest"
///    },
///    "CapabilityProfileRequest": {
///      "$ref": "#/definitions/CapabilityProfileRequest"
///    },
///    "CatalogEnvelope": {
///      "$ref": "#/definitions/CatalogEnvelope"
///    },
///    "CompileRequest": {
///      "$ref": "#/definitions/CompileRequest"
///    },
///    "CompiledInteraction": {
///      "$ref": "#/definitions/CompiledInteraction"
///    },
///    "CompiledInteractionEnvelope": {
///      "$ref": "#/definitions/CompiledInteractionEnvelope"
///    },
///    "Contract": {
///      "$ref": "#/definitions/Contract"
///    },
///    "ContractEnvelope": {
///      "$ref": "#/definitions/ContractEnvelope"
///    },
///    "ContractSummary": {
///      "$ref": "#/definitions/ContractSummary"
///    },
///    "CreatePackageRequest": {
///      "$ref": "#/definitions/CreatePackageRequest"
///    },
///    "Diagnostic": {
///      "$ref": "#/definitions/Diagnostic"
///    },
///    "DiffContractRequest": {
///      "$ref": "#/definitions/DiffContractRequest"
///    },
///    "ExecuteRequest": {
///      "$ref": "#/definitions/ExecuteRequest"
///    },
///    "ExecutionReceipt": {
///      "$ref": "#/definitions/ExecutionReceipt"
///    },
///    "ExecutionReceiptEnvelope": {
///      "$ref": "#/definitions/ExecutionReceiptEnvelope"
///    },
///    "FieldSpec": {
///      "$ref": "#/definitions/FieldSpec"
///    },
///    "HealthStatus": {
///      "$ref": "#/definitions/HealthStatus"
///    },
///    "InspectDocumentEnvelope": {
///      "$ref": "#/definitions/InspectDocumentEnvelope"
///    },
///    "InspectDocumentRequest": {
///      "$ref": "#/definitions/InspectDocumentRequest"
///    },
///    "InspectDocumentResult": {
///      "$ref": "#/definitions/InspectDocumentResult"
///    },
///    "JsonValue": {
///      "$ref": "#/definitions/JsonValue"
///    },
///    "JsonValueEnvelope": {
///      "$ref": "#/definitions/JsonValueEnvelope"
///    },
///    "MigrateLegacyRequest": {
///      "$ref": "#/definitions/MigrateLegacyRequest"
///    },
///    "OperationEnvelopeBase": {
///      "$ref": "#/definitions/OperationEnvelopeBase"
///    },
///    "PackageEnvelope": {
///      "$ref": "#/definitions/PackageEnvelope"
///    },
///    "PackageListEnvelope": {
///      "$ref": "#/definitions/PackageListEnvelope"
///    },
///    "PackageManifest": {
///      "$ref": "#/definitions/PackageManifest"
///    },
///    "PackageSignature": {
///      "$ref": "#/definitions/PackageSignature"
///    },
///    "RenderDocumentRequest": {
///      "$ref": "#/definitions/RenderDocumentRequest"
///    },
///    "RenderRequest": {
///      "$ref": "#/definitions/RenderRequest"
///    },
///    "RunEvalRequest": {
///      "$ref": "#/definitions/RunEvalRequest"
///    },
///    "SignPackageRequest": {
///      "$ref": "#/definitions/SignPackageRequest"
///    },
///    "SourceSpan": {
///      "$ref": "#/definitions/SourceSpan"
///    },
///    "StreamEvent": {
///      "$ref": "#/definitions/StreamEvent"
///    },
///    "StringListEnvelope": {
///      "$ref": "#/definitions/StringListEnvelope"
///    },
///    "SummaryEnvelope": {
///      "$ref": "#/definitions/SummaryEnvelope"
///    },
///    "TransportError": {
///      "$ref": "#/definitions/TransportError"
///    },
///    "UpdatePackageRequest": {
///      "$ref": "#/definitions/UpdatePackageRequest"
///    },
///    "VerifyPackageTrustRequest": {
///      "$ref": "#/definitions/VerifyPackageTrustRequest"
///    }
///  }
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
pub struct TempliqxOperationsV1 {
    #[serde(
        rename = "AdapterDescriptor",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub adapter_descriptor: ::std::option::Option<AdapterDescriptor>,
    #[serde(
        rename = "CapabilitiesRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub capabilities_request: ::std::option::Option<CapabilitiesRequest>,
    #[serde(
        rename = "CapabilityProfileRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub capability_profile_request: ::std::option::Option<CapabilityProfileRequest>,
    #[serde(
        rename = "CatalogEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub catalog_envelope: ::std::option::Option<CatalogEnvelope>,
    #[serde(
        rename = "CompileRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub compile_request: ::std::option::Option<CompileRequest>,
    #[serde(
        rename = "CompiledInteraction",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub compiled_interaction: ::std::option::Option<CompiledInteraction>,
    #[serde(
        rename = "CompiledInteractionEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub compiled_interaction_envelope: ::std::option::Option<CompiledInteractionEnvelope>,
    #[serde(
        rename = "Contract",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub contract: ::std::option::Option<Contract>,
    #[serde(
        rename = "ContractEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub contract_envelope: ::std::option::Option<ContractEnvelope>,
    #[serde(
        rename = "ContractSummary",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub contract_summary: ::std::option::Option<ContractSummary>,
    #[serde(
        rename = "CreatePackageRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub create_package_request: ::std::option::Option<CreatePackageRequest>,
    #[serde(
        rename = "Diagnostic",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub diagnostic: ::std::option::Option<Diagnostic>,
    #[serde(
        rename = "DiffContractRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub diff_contract_request: ::std::option::Option<DiffContractRequest>,
    #[serde(
        rename = "ExecuteRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub execute_request: ::std::option::Option<ExecuteRequest>,
    #[serde(
        rename = "ExecutionReceipt",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub execution_receipt: ::std::option::Option<ExecutionReceipt>,
    #[serde(
        rename = "ExecutionReceiptEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub execution_receipt_envelope: ::std::option::Option<ExecutionReceiptEnvelope>,
    #[serde(
        rename = "FieldSpec",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub field_spec: ::std::option::Option<FieldSpec>,
    #[serde(
        rename = "HealthStatus",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub health_status: ::std::option::Option<HealthStatus>,
    #[serde(
        rename = "InspectDocumentEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub inspect_document_envelope: ::std::option::Option<InspectDocumentEnvelope>,
    #[serde(
        rename = "InspectDocumentRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub inspect_document_request: ::std::option::Option<InspectDocumentRequest>,
    #[serde(
        rename = "InspectDocumentResult",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub inspect_document_result: ::std::option::Option<InspectDocumentResult>,
    #[serde(
        rename = "JsonValue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub json_value: ::std::option::Option<JsonValue>,
    #[serde(
        rename = "JsonValueEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub json_value_envelope: ::std::option::Option<JsonValueEnvelope>,
    #[serde(
        rename = "MigrateLegacyRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub migrate_legacy_request: ::std::option::Option<MigrateLegacyRequest>,
    #[serde(
        rename = "OperationEnvelopeBase",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub operation_envelope_base: ::std::option::Option<OperationEnvelopeBase>,
    #[serde(
        rename = "PackageEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub package_envelope: ::std::option::Option<PackageEnvelope>,
    #[serde(
        rename = "PackageListEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub package_list_envelope: ::std::option::Option<PackageListEnvelope>,
    #[serde(
        rename = "PackageManifest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub package_manifest: ::std::option::Option<PackageManifest>,
    #[serde(
        rename = "PackageSignature",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub package_signature: ::std::option::Option<PackageSignature>,
    #[serde(
        rename = "RenderDocumentRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub render_document_request: ::std::option::Option<RenderDocumentRequest>,
    #[serde(
        rename = "RenderRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub render_request: ::std::option::Option<RenderRequest>,
    #[serde(
        rename = "RunEvalRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub run_eval_request: ::std::option::Option<RunEvalRequest>,
    #[serde(
        rename = "SignPackageRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub sign_package_request: ::std::option::Option<SignPackageRequest>,
    #[serde(
        rename = "SourceSpan",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub source_span: ::std::option::Option<SourceSpan>,
    #[serde(
        rename = "StreamEvent",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub stream_event: ::std::option::Option<StreamEvent>,
    #[serde(
        rename = "StringListEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub string_list_envelope: ::std::option::Option<StringListEnvelope>,
    #[serde(
        rename = "SummaryEnvelope",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub summary_envelope: ::std::option::Option<SummaryEnvelope>,
    #[serde(
        rename = "TransportError",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub transport_error: ::std::option::Option<TransportError>,
    #[serde(
        rename = "UpdatePackageRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub update_package_request: ::std::option::Option<UpdatePackageRequest>,
    #[serde(
        rename = "VerifyPackageTrustRequest",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub verify_package_trust_request: ::std::option::Option<VerifyPackageTrustRequest>,
}
impl ::std::default::Default for TempliqxOperationsV1 {
    fn default() -> Self {
        Self {
            adapter_descriptor: Default::default(),
            capabilities_request: Default::default(),
            capability_profile_request: Default::default(),
            catalog_envelope: Default::default(),
            compile_request: Default::default(),
            compiled_interaction: Default::default(),
            compiled_interaction_envelope: Default::default(),
            contract: Default::default(),
            contract_envelope: Default::default(),
            contract_summary: Default::default(),
            create_package_request: Default::default(),
            diagnostic: Default::default(),
            diff_contract_request: Default::default(),
            execute_request: Default::default(),
            execution_receipt: Default::default(),
            execution_receipt_envelope: Default::default(),
            field_spec: Default::default(),
            health_status: Default::default(),
            inspect_document_envelope: Default::default(),
            inspect_document_request: Default::default(),
            inspect_document_result: Default::default(),
            json_value: Default::default(),
            json_value_envelope: Default::default(),
            migrate_legacy_request: Default::default(),
            operation_envelope_base: Default::default(),
            package_envelope: Default::default(),
            package_list_envelope: Default::default(),
            package_manifest: Default::default(),
            package_signature: Default::default(),
            render_document_request: Default::default(),
            render_request: Default::default(),
            run_eval_request: Default::default(),
            sign_package_request: Default::default(),
            source_span: Default::default(),
            stream_event: Default::default(),
            string_list_envelope: Default::default(),
            summary_envelope: Default::default(),
            transport_error: Default::default(),
            update_package_request: Default::default(),
            verify_package_trust_request: Default::default(),
        }
    }
}
///`TransportError`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "required": [
///    "code",
///    "message"
///  ],
///  "properties": {
///    "code": {
///      "examples": [
///        "TQX_TRANSPORT_TIMEOUT"
///      ],
///      "type": "string"
///    },
///    "message": {
///      "type": "string"
///    },
///    "request_id": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct TransportError {
    pub code: ::std::string::String,
    pub message: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub request_id: ::std::option::Option<::std::string::String>,
}
///`UpdatePackageRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "minProperties": 1,
///  "properties": {
///    "description": {
///      "type": "string"
///    },
///    "version": {
///      "type": "string"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct UpdatePackageRequest {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub description: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub version: ::std::option::Option<::std::string::String>,
}
impl ::std::default::Default for UpdatePackageRequest {
    fn default() -> Self {
        Self {
            description: Default::default(),
            version: Default::default(),
        }
    }
}
///`VerifyPackageTrustRequest`
///
/// <details><summary>JSON schema</summary>
///
/// ```json
///{
///  "type": "object",
///  "properties": {
///    "strict": {
///      "default": false,
///      "type": "boolean"
///    }
///  },
///  "additionalProperties": false
///}
/// ```
/// </details>
#[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct VerifyPackageTrustRequest {
    #[serde(default)]
    pub strict: bool,
}
impl ::std::default::Default for VerifyPackageTrustRequest {
    fn default() -> Self {
        Self {
            strict: Default::default(),
        }
    }
}
/// Generation of default values for serde.
pub mod defaults {
    pub(super) fn inspect_document_request_aliases() -> super::JsonValue {
        super::JsonValue(::serde_json::from_str::<::serde_json::Value>("{}").unwrap())
    }
}

/// Codegen metadata used by the compatibility self-check.
pub const GENERATED_OPENAPI_VERSION: &str = "1.0.0-alpha.1";
pub const GENERATED_OPENAPI_DIGEST: &str =
    "sha256:7cd1c2251d87c27a77efcc35523209d8916cc59d222c8f770b095ecc078a1914";
pub const GENERATED_CONTRACT_FORMAT: &str = "templiqx/v1alpha1";
pub const GENERATED_ENGINE_VERSION: &str = "0.1.0";
pub const GENERATED_SDK_VERSION: &str = "0.1.0";
